/*
World countries names (in Russian and English) and codes according to ISO 3166 
(http://www.iso.org/iso/country_codes.htm) and Russian OKSM standards
Author: Alex Zakharov
Date: 2/10/2008
*/

if not exists (select * from sysobjects where id = object_id(N'fx.Countries') and xtype ='U')
begin

CREATE TABLE fx.Countries (
	CountryID smallint not null identity(1,1),
	CountryCode char(3) not null,
	ShortNameRus nvarchar(256) not null,
	FullNameRus nvarchar(512),
	NameEng nvarchar(512) not null,
	Alfa2 char(2) not null,
	Alfa3 char(3) not null
	CONSTRAINT PK_Countries PRIMARY KEY CLUSTERED (CountryID ASC)
)		

CREATE NONCLUSTERED INDEX IX_CountriesShortNameRus ON fx.Countries(ShortNameRus)
CREATE NONCLUSTERED INDEX IX_CountriesNameEng ON fx.Countries(NameEng)

EXEC sys.sp_addextendedproperty @name=N'MS_Description', 
	@value=N'World countries names (in Russian and English) and codes according to ISO 3166 (http://www.iso.org/iso/country_codes.htm) and Russian OKSM standards', 
	@level0type=N'SCHEMA', @level0name=N'fx', @level1type=N'TABLE',  @level1name=N'Countries'
EXEC sys.sp_addextendedproperty @name=N'MS_Description', 
	@value=N'Country numeric code' , 
	@level0type=N'SCHEMA', @level0name=N'fx', @level1type=N'TABLE',  @level1name=N'Countries', @level2type=N'COLUMN',  @level2name=N'CountryCode'
EXEC sys.sp_addextendedproperty @name=N'MS_Description', 
	@value=N'Country two-symbols code. Used for national internet domains' , 
	@level0type=N'SCHEMA', @level0name=N'fx', @level1type=N'TABLE',  @level1name=N'Countries', @level2type=N'COLUMN',  @level2name=N'Alfa2'
EXEC sys.sp_addextendedproperty @name=N'MS_Description', 
	@value=N'Country three-symbols code. Used for national internet domains' , 
	@level0type=N'SCHEMA', @level0name=N'fx', @level1type=N'TABLE',  @level1name=N'Countries', @level2type=N'COLUMN',  @level2name=N'Alfa3'
EXEC sys.sp_addextendedproperty @name=N'MS_Description', 
	@value=N'Country short name in Russian' , 
	@level0type=N'SCHEMA', @level0name=N'fx', @level1type=N'TABLE',  @level1name=N'Countries', @level2type=N'COLUMN',  @level2name=N'ShortNameRus'
EXEC sys.sp_addextendedproperty @name=N'MS_Description', 
	@value=N'Country full name in Russian' , 
	@level0type=N'SCHEMA', @level0name=N'fx', @level1type=N'TABLE',  @level1name=N'Countries', @level2type=N'COLUMN',  @level2name=N'FullNameRus'
EXEC sys.sp_addextendedproperty @name=N'MS_Description', 
	@value=N'Country short name in English' , 
	@level0type=N'SCHEMA', @level0name=N'fx', @level1type=N'TABLE',  @level1name=N'Countries', @level2type=N'COLUMN',  @level2name=N'NameEng'

INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('004', N'Афганистан', N'', N'Afghanistan', 'AF', 'AFG')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('008', N'Албания', N'Республика Албания', N'Albania', 'AL', 'ALB')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('010', N'Антарктида', N'', N'Antarctica', 'AQ', 'ATA')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('012', N'Алжир', N'Алжирская   Народная  Демократическая Республика', N'Algeria', 'DZ', 'DZA')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('016', N'Американское Самоа', N'', N'American Samoa', 'AS', 'ASM')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('020', N'Андорра', N'Княжество Андорра', N'Andorra', 'AD', 'AND')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('024', N'Ангола', N'Республика Ангола', N'Angola', 'AO', 'AGO')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('028', N'Антигуа и Барбуда', N'', N'Antigua & Barbuda', 'AG', 'ATG')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('031', N'Азербайджан', N'Республика Азербайджан', N'Azerbaijan', 'AZ', 'AZE')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('032', N'Аргентина', N'Аргентинская Республика', N'Argentina', 'AR', 'ARG')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('036', N'Австралия', N'', N'Australia', 'AU', 'AUS')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('040', N'Австрия', N'Австрийская Республика', N'Austria', 'AT', 'AUT')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('044', N'Багамы', N'Содружество Багамы', N'Bahama', 'BS', 'BHS')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('048', N'Бахрейн', N'Королевство Бахрейн', N'Bahrain', 'BH', 'BHR')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('050', N'Бангладеш', N'Народная Республика Бангладеш ', N'Bangladesh', 'BD', 'BGD')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('051', N'Армения', N'Республика Армения', N'Armenia', 'AM', 'ARM')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('052', N'Барбадос', N'', N'Barbados', 'BB', 'BRB')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('056', N'Бельгия', N'Королевство Бельгии', N'Belgium', 'BE', 'BEL')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('060', N'Бермуды', N'', N'Bermuda', 'BM', 'BMU')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('064', N'Бутан', N'Королевство Бутан', N'Bhutan', 'BT', 'BTN')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('068', N'Боливия', N'Республика Боливия', N'Bolivia', 'BO', 'BOL')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('070', N'Босния и Герцеговина', N'', N'Bosnia and Herzegovina', 'BA', 'BIH')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('072', N'Ботсвана', N'Республика Ботсвана', N'Botswana', 'BW', 'BWA')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('074', N'Остров Буве', N'', N'Bouvet Island', 'BV', 'BVT')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('076', N'Бразилия', N'Федеративная Республика Бразилия', N'Brazil', 'BR', 'BRA')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('084', N'Белиз', N'', N'Belize', 'BZ', 'BLZ')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('086', N'Британская территория в Индийском океане', N'', N'British Indian Ocean Territory', 'IO', 'IOT')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('090', N'Соломоновы Острова', N'', N'Solomon Islands', 'SB', 'SLB')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('092', N'Виргинские Острова, Британские  ', N'Британские Виргинские острова ', N'British Virgin Islands', 'VG', 'VGB')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('096', N'Бруней-Даруссалам', N'', N'Brunei Darussalam', 'BN', 'BRN')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('100', N'Болгария', N'Республика Болгария', N'Bulgaria', 'BG', 'BGR')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('104', N'Мьянма', N'Союз Мьянма  ', N'Myanmar', 'MM', 'MMR')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('108', N'Бурунди', N'Республика Бурунди', N'Burundi', 'BI', 'BDI')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('112', N'Беларусь', N'Республика Беларусь', N'Belarus', 'BY', 'BLR')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('116', N'Камбоджа', N'Королевство Камбоджа', N'Cambodia', 'KH', 'KHM')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('120', N'Камерун', N'Республика Камерун', N'Cameroon', 'CM', 'CMR')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('124', N'Канада', N'', N'Canada', 'CA', 'CAN')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('132', N'Кабо-Верде', N'Республика Кабо-Верде', N'Cape Verde', 'CV', 'CPV')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('136', N'Острова Кайман  ', N'', N'Cayman Islands', 'KY', 'CYM')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('140', N'Центрально-Африканская Республика', N'', N'Central African Republic', 'CF', 'CAF')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('144', N'Шри-Ланка', N'Демократическая     Социалистическая Республика Шри-Ланка', N'Sri Lanka', 'LK', 'LKA')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('148', N'Чад', N'Республика Чад ', N'Chad', 'TD', 'TCD')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('152', N'Чили', N'Республика Чили', N'Chile', 'CL', 'CHL')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('156', N'Китай', N'Китайская Народная Республика ', N'China', 'CN', 'CHN')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('158', N'Тайвань (Китай) ', N'', N'Taiwan, Province of China', 'TW', 'TWN')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('162', N'Остров Рождества ', N'', N'Christmas Island', 'CX', 'CXR')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('166', N'Кокосовые (Килинг) острова', N'', N'Cocos (Keeling) Islands', 'CC', 'CCK')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('170', N'Колумбия', N'Республика Колумбия', N'Colombia', 'CO', 'COL')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('174', N'Коморы', N'Союз Коморы', N'Comorres', '??', 'COM')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('175', N'Майотта', N'', N'Mayotte', 'YT', 'MYT')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('178', N'Конго', N'Республика Конго', N'Congo', 'CG', 'COG')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('180', N'Конго, демократическая республика', N'Демократическая Республика Конго', N'Congo, Democratic Republic of', 'CD', 'COD')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('184', N'Острова Кука', N'', N'Cook Iislands', 'CK', 'COK')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('188', N'Коста-Рика', N'Республика Коста-Рика', N'Costa Rica', 'CR', 'CRI')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('191', N'Хорватия', N'Республика Хорватия', N'Croatia', 'HR', 'HRV')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('192', N'Куба', N'Республика Куба', N'Cuba', 'CU', 'CUB')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('196', N'Кипр', N'Республика Кипр', N'Cyprus', 'CY', 'CYP')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('203', N'Чешская Республика', N'', N'Czech Republic', 'CZ', 'CZE')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('204', N'Бенин', N'Республика Бенин', N'Benin', 'BJ', 'BEN')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('208', N'Дания', N'Королевство Дания', N'Denmark', 'DK', 'DNK')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('212', N'Доминика', N'Содружество Доминики', N'Dominica', 'DM', 'DMA')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('214', N'Доминиканская Республика', N'', N'Dominican Republic', 'DO', 'DOM')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('218', N'Эквадор', N'Республика Эквадор', N'Ecuador', 'EC', 'ECU')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('222', N'Эль-Сальвадор  ', N'Республика Эль-Сальвадор', N'El Salvador', 'SV', 'SLV')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('226', N'Экваториальная Гвинея', N'Республика Экваториальная Гвинея', N'Equatorial Guinea', 'GQ', 'GNQ')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('231', N'Эфиопия', N'Федеративная Демократическая Республика Эфиопия', N'Ethiopia', 'ET', 'ETH')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('232', N'Эритрея', N'', N'Eritrea', 'ER', 'ERI')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('233', N'Эстония', N'Эстонская Республика', N'Estonia', 'EE', 'EST')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('234', N'Фарерские острова', N'', N'Faroe Islands', 'FO', 'FRO')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('238', N'Фолклендские острова (Мальвинские)', N'', N'Falkland Islands (Malvinas)', 'FK', 'FLK')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('239', N'Южная Джорджия и Южные Сандвичевы острова', N'', N'South Georgia and the South Sandwich Islands', 'GS', 'SGS')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('242', N'Фиджи', N'Республика Островов Фиджи', N'Fiji', 'FJ', 'FJI')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('246', N'Финляндия', N'Финляндская Республика', N'Finland', 'FI', 'FIN')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('250', N'Франция', N'Французская Республика', N'France', 'FR', 'FRA')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('254', N'Французская Гвиана', N'', N'French Guiana', 'GF', 'GUF')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('258', N'Французская Полинезия', N'', N'French Polynesia', 'PF', 'PYF')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('260', N'Французские Южные территории', N'', N'French Southern Territories', 'TF', 'ATF')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('262', N'Джибути', N'Республика Джибути', N'Djibouti', 'DJ', 'DJI')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('266', N'Габон', N'Габонская Республика', N'Gabon', 'GA', 'GAB')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('268', N'Грузия', N'', N'Georgia', 'GE', 'GEO')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('270', N'Гамбия', N'Республика Гамбия', N'Gambia', 'GM', 'GMB')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('275', N'Палестинская территория, оккупированная', N'Окупированная Палестинская территория', N'Palestinian', 'PS', 'PSE')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('276', N'Германия', N'Федеративная Республика Германия', N'Germany', 'DE', 'DEU')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('288', N'Гана', N'Республика Гана', N'Ghana', 'GH', 'GHA')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('292', N'Гибралтар', N'', N'Gibraltar', 'GI', 'GIB')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('296', N'Кирибати', N'Республика Кирибати', N'Kiribati', 'KI', 'KIR')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('300', N'Греция', N'Греческая Республика', N'Greece', 'GR', 'GRC')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('304', N'Гренландия', N'', N'Greenland', 'GL', 'GRL')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('308', N'Гренада', N'', N'Grenada', 'GD', 'GRD')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('312', N'Гваделупа', N'', N'Guadeloupe', 'GP', 'GLP')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('316', N'Гуам', N'', N'Guam', 'GU', 'GUM')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('320', N'Гватемала', N'Республика Гватемала', N'Guatemala', 'GT', 'GTM')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('324', N'Гвинея', N'Гвинейская Республика', N'Guinea', 'GN', 'GIN')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('328', N'Гайана', N'Республика Гайана', N'Guyana', 'GY', 'GUY')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('332', N'Гаити', N'Республика Гаити', N'Haiti', 'HT', 'HTI')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('334', N'Остров Херд и острова Макдональд ', N'', N'Heard & McDonald Islands', 'HM', 'HMD')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('336', N'Папский Престол (Государство-город Ватикан)', N'', N'Vatican City State (Holy See)', 'VA', 'VAT')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('340', N'Гондурас', N'Республика Гондурас', N'Honduras', 'HN', 'HND')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('344', N'Гонконг', N'Специальный административный регион Китая Гонконг', N'Hong Kong', 'HK', 'HKG')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('348', N'Венгрия', N'Венгерская Республика', N'Hungary', 'HU', 'HUN')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('352', N'Исландия', N'Республика Исландия', N'Iceland', 'IS', 'ISL')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('356', N'Индия', N'Республика Индия', N'India', 'IN', 'IND')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('360', N'Индонезия', N'Республика Индонезия', N'Indonesia', 'ID', 'IDN')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('364', N'Иран, исламская республика', N'Исламская Республика Иран', N'Iran', 'IR', 'IRN')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('368', N'Ирак', N'Республика Ирак', N'Iraq', 'IQ', 'IRQ')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('372', N'Ирландия', N'', N'Ireland', 'IE', 'IRL')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('376', N'Израиль', N'Государство Израиль', N'Israel', 'IL', 'ISR')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('380', N'Италия', N'Итальянская Республика', N'Italy', 'IT', 'ITA')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('384', N'Кот Д Ивуар', N'Республика Кот Д Ивуар', N'C?te D ivoire (Ivory Coast)', 'CI', 'CIV')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('388', N'Ямайка', N'', N'Jamaica', 'JM', 'JAM')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('392', N'Япония', N'', N'Japan', 'JP', 'JPN')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('398', N'Казахстан', N'Республика Казахстан', N'Kazakhstan', 'KZ', 'KAZ')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('400', N'Иордания', N'Иорданское Хашимитское Королевство', N'Jordan', 'JO', 'JOR')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('404', N'Кения', N'Республика Кения', N'Kenya', 'KE', 'KEN')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('408', N'Корея, народно-демократическая республика', N'Корейская     Народно-Демократическая Республика', N'Korea, Democratic People s Republic of', 'KP', 'PRK')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('410', N'Корея, республика', N'Республика Корея', N'Korea, Republic of', 'KR', 'KOR')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('414', N'Кувейт', N'Государство Кувейт', N'Kuwait', 'KW', 'KWT')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('417', N'Киргизия', N'Киргизская Республика', N'Kyrgyzstan', 'KG', 'KGZ')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('418', N'Лаосская Народно-Демократическая Республика', N'', N'Lao People s Democratic Republic', 'LA', 'LAO')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('422', N'Ливан', N'Ливанская Республика', N'Lebanon', 'LB', 'LBN')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('426', N'Лесото', N'Королевство Лесото', N'Lesotho', 'LS', 'LSO')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('428', N'Латвия', N'Латвийская Республика', N'Latvia', 'LV', 'LVA')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('430', N'Либерия', N'Республика Либерия', N'Liberia', 'LR', 'LBR')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('434', N'Ливийская Арабская Джамахирия  ', N'Социалистическая Народная         Ливийская Арабская Джамахирия ', N'Libyan Arab Jamahiriya', 'LY', 'LBY')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('438', N'Лихтенштейн', N'Княжество Лихтенштейн', N'Liechtenstein', 'LI', 'LIE')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('440', N'Литва', N'Литовская Республика', N'Lithuania', 'LT', 'LTU')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('442', N'Люксембург', N'Великое Герцогство Люксембург ', N'Luxembourg', 'LU', 'LUX')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('446', N'Макао', N'Специальный административный регион Китая Макао', N'Macau', 'MO', 'MAC')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('450', N'Мадагаскар', N'Республика Мадагаскар', N'Madagascar', 'MG', 'MDG')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('454', N'Малави', N'Республика Малави', N'Malawi', 'MW', 'MWI')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('458', N'Малайзия', N'', N'Malaysia', 'MY', 'MYS')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('462', N'Мальдивы', N'Мальдивская Республика', N'Maldives', 'MV', 'MDV')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('466', N'Мали', N'Республика Мали', N'Mali', 'ML', 'MLI')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('470', N'Мальта', N'Республика Мальта', N'Malta', 'MT', 'MLT')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('474', N'Мартиника', N'', N'Martinique', 'MQ', 'MTQ')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('478', N'Мавритания', N'Исламская Республика Мавритания', N'Mauritania', 'MR', 'MRT')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('480', N'Маврикий', N'Республика Маврикий', N'Mauritius', 'MU', 'MUS')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('484', N'Мексика', N'Мексиканские Соединенные Штаты ', N'Mexico', 'MX', 'MEX')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('492', N'Монако', N'Княжество Монако', N'Monaco', 'MC', 'MCO')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('496', N'Монголия', N'', N'Mongolia', 'MN', 'MNG')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('498', N'Молдова, республика', N'Республика Молдова', N'Moldova, Republic of', 'MD', 'MDA')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('500', N'Монтсеррат', N'', N'Monserrat', 'MS', 'MSR')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('504', N'Марокко', N'Королевство Марокко', N'Morocco', 'MA', 'MAR')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('508', N'Мозамбик', N'Республика Мозамбик', N'Mozambique', 'MZ', 'MOZ')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('512', N'Оман', N'Султанат Оман ', N'Oman', 'OM', 'OMN')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('516', N'Намибия', N'Республика Намибия', N'Namibia', 'NA', 'NAM')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('520', N'Науру', N'Республика Науру', N'Nauru', 'NR', 'NRU')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('524', N'Непал', N'Королевство Непал', N'Nepal', 'NP', 'NPL')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('528', N'Нидерланды', N'Королевство Нидерландов', N'Netherlands', 'NL', 'NLD')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('530', N'Нидерландские Антилы', N'', N'Netherlands Antilles', 'AN', 'ANT')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('533', N'Аруба', N'', N'Aruba', 'AW', 'ABW')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('540', N'Новая Каледония ', N'', N'New Caledonia', 'NC', 'NCL')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('548', N'Вануату', N'Республика Вануату', N'Vanuatu', 'VU', 'VUT')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('554', N'Новая Зеландия  ', N'', N'New Zealand', 'NZ', 'NZL')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('558', N'Никарагуа', N'Республика Никарагуа', N'Nicaragua', 'NI', 'NIC')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('562', N'Нигер', N'Республика Нигер', N'Niger', 'NE', 'NER')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('566', N'Нигерия', N'Федеративная Республика Нигерия', N'Nigeria', 'NG', 'NGA')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('570', N'Ниуэ', N'Республика Ниуэ', N'Niue', 'NU', 'NIU')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('574', N'Остров Норфолк  ', N'', N'Norfolk Island', 'NF', 'NFK')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('578', N'Норвегия', N'Королевство Норвегия', N'Norway', 'NO', 'NOR')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('580', N'Северные Марианские острова', N'Содружество Северных Марианских островов', N'Northern Mariana Islands', 'MP', 'MNP')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('581', N'Малые Тихоокеанские  отдаленные  острова', N'Соединенных Штатов', N'United States Minor Outlying Islands', 'UM', 'UMI')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('583', N'Микронезия, Федеративные Штаты  ', N'Федеративные Штаты Микронезии ', N'Micronesia', 'FM', 'FSM')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('584', N'Маршалловы Острова', N'Республика Маршалловы Острова ', N'Marshall Islands', 'MH', 'MHL')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('585', N'Палау', N'Республика Палау', N'Palau', 'PW', 'PLW')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('586', N'Пакистан', N'Исламская Республика Пакистан ', N'Pakistan', 'PK', 'PAK')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('591', N'Панама', N'Республика Панама', N'Panama', 'PA', 'PAN')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('598', N'Папуа-Новая Гвинея', N'', N'Papua New Guinea', 'PG', 'PNG')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('600', N'Парагвай', N'Республика Парагвай', N'Paraguay', 'PY', 'PRY')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('604', N'Перу', N'Республика Перу', N'Peru', 'PE', 'PER')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('608', N'Филиппины', N'Республика Филиппины', N'Philippines', 'PH', 'PHL')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('612', N'Питкерн', N'', N'Pitcairn', 'PN', 'PCN')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('616', N'Польша', N'Республика Польша', N'Poland', 'PL', 'POL')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('620', N'Португалия', N'Португальская Республика', N'Portugal', 'PT', 'PRT')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('624', N'Гвинея-Бисау', N'Республика Гвинея-Бисау', N'Guinea-Bissau', 'GW', 'GNB')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('626', N'Тимор-Лесте', N'Демократическая Республика Тимор-Лесте', N'Timour', 'TL', 'TLS')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('630', N'Пуэрто-Рико', N'', N'Puerto Rico', 'PR', 'PRI')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('634', N'Катар', N'Государство Катар', N'Qatar', 'QA', 'QAT')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('638', N'Реюньон', N'', N'R?union', 'RE', 'REU')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('642', N'Румыния', N'', N'Romania', 'RO', 'ROU')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('643', N'Россия', N'Российская Федерация', N'Russian Federation', 'RU', 'RUS')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('646', N'Руанда', N'Руандийская Республика', N'Rwanda', 'RW', 'RWA')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('654', N'Святая Елена', N'', N'St. Helena', 'SH', 'SHN')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('659', N'Сент-Китс и Невис', N'', N'St. Kitts and Nevis', 'KN', 'KNA')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('660', N'Ангилья', N'', N'Anguilla', 'AI', 'AIA')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('662', N'Сент-Люсия', N'', N'Saint Lucia', 'LC', 'LCA')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('666', N'Сент-Пьер и Микелон', N'', N'St. Pierre & Miquelon', 'PM', 'SPM')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('670', N'Сент-Винсент и Гренадины', N'', N'St. Vincent & the Grenadines', 'VC', 'VCT')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('674', N'Сан-Марино', N'Республика Сан-Марино', N'San Marino', 'SM', 'SMR')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('678', N'Сан-Томе и Принсипи', N'Демократическая Республика  Сан-Томе и Принсипи', N'Sao Tome & Principe', 'ST', 'STP')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('682', N'Саудовская Аравия', N'Королевство Саудовская Аравия ', N'Saudi Arabia', 'SA', 'SAU')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('686', N'Сенегал', N'Республика Сенегал', N'Senegal', 'SN', 'SEN')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('690', N'Сейшелы', N'Республика Сейшелы', N'Seychelles', 'SC', 'SYC')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('694', N'Сьерра-Леоне', N'Республика Сьерра-Леоне', N'Sierra Leone', 'SL', 'SLE')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('702', N'Сингапур', N'Республика Сингапур', N'Singapore', 'SG', 'SGP')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('703', N'Словакия', N'Словацкая Республика', N'Slovakia', 'SK', 'SVK')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('704', N'Вьетнам', N'Социалистическая Республика Вьетнам', N'Viet Nam', 'VN', 'VNM')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('705', N'Словения', N'Республика Словения', N'Slovenia', 'SI', 'SVN')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('706', N'Сомали', N'Сомалийская Республика', N'Somalia', 'SO', 'SOM')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('710', N'Южная Африка', N'Южно-Африканская Республика  ', N'South Africa', 'ZA', 'ZAF')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('716', N'Зимбабве', N'Республика Зимбабве', N'Zimbabwe', 'ZW', 'ZWE')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('724', N'Испания', N'Королевство Испания', N'Spain', 'ES', 'ESP')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('732', N'Западная Сахара ', N'', N'Western Sahara', 'EH', 'ESH')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('736', N'Судан', N'Республика Судан', N'Sudan', 'SD', 'SDN')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('740', N'Суринам', N'Республика Суринам', N'Suriname', 'SR', 'SUR')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('744', N'Шпицберген и Ян Майен', N'', N'Svalbard & Jan Mayen Islands', 'SJ', 'SJM')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('748', N'Свазиленд', N'Королевство Свазиленд', N'Swaziland', 'SZ', 'SWZ')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('752', N'Швеция', N'Королевство Швеция', N'Sweden', 'SE', 'SWE')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('756', N'Швейцария', N'Швейцарская Конфедерация', N'Switzerland', 'CH', 'CHE')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('760', N'Сирийская Арабская Республика  ', N'', N'Syrian Arab Republic', 'SY', 'SYR')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('762', N'Таджикистан', N'Республика Таджикистан', N'Tajikistan', 'TJ', 'TJK')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('764', N'Таиланд', N'Королевство Таиланд', N'Thailand', 'TH', 'THA')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('768', N'Того', N'Тоголезская Республика', N'Togo', 'TG', 'TGO')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('772', N'Токелау', N'', N'Tokelau', 'TK', 'TKL')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('776', N'Тонга', N'Королевство Тонга', N'Tonga', 'TO', 'TON')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('780', N'Тринидад и Тобаго', N'Республика Тринидад и Тобаго  ', N'Trinidad & Tobago', 'TT', 'TTO')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('784', N'Объединенные Арабские Эмираты  ', N'', N'United Arab Emirates', 'AE', 'ARE')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('788', N'Тунис', N'Тунисская Республика', N'Tunisia', 'TN', 'TUN')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('792', N'Турция', N'Турецкая Республика', N'Turkey', 'TR', 'TUR')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('795', N'Туркмения', N'Туркменистан  ', N'Turkmenistan', 'TM', 'TKM')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('796', N'Острова Теркс и Кайкос', N'', N'Turks & Caicos Islands', 'TC', 'TCA')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('798', N'Тувалу', N'', N'Tuvalu', 'TV', 'TUV')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('800', N'Уганда', N'Республика Уганда', N'Uganda', 'UG', 'UGA')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('804', N'Украина', N'', N'Ukraine', 'UA', 'UKR')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('807', N'Македония, бывшая Югославская Республика', N'Бывшая Югославская Республика Македония', N'Makedonia', 'MK', 'MKD')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('818', N'Египет', N'Арабская Республика Египет', N'Egypt', 'EG', 'EGY')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('826', N'Соединенное Королевство', N'Соединенное Королевство Великобритании и Северной Ирландии', N'United Kingdom (Great Britain)', 'GB', 'GBR')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('834', N'Танзания, объединенная республика', N'Объединенная Республика Танзания', N'Tanzania, United Republic of', 'TZ', 'TZA')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('840', N'Соединенные Штаты', N'Соединенные Штаты Америки', N'United States of America', 'US', 'USA')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('850', N'Виргинские острова, США', N'Виргинские острова Соединенных Штатов', N'United States Virgin Islands', 'VI', 'VIR')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('854', N'Буркина-Фасо', N'', N'Burkina Faso', 'BF', 'BFA')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('858', N'Уругвай', N'Восточная Республика Уругвай  ', N'Uruguay', 'UY', 'URY')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('860', N'Узбекистан', N'Республика Узбекистан', N'Uzbekistan', 'UZ', 'UZB')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('862', N'Венесуэла', N'Боливарийская Республика Венесуэла', N'Venezuela', 'VE', 'VEN')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('876', N'Уоллис и Футуна ', N'', N'Wallis & Futuna Islands', 'WF', 'WLF')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('882', N'Самоа', N'Независимое Государство Самоа ', N'Samoa', 'WS', 'WSM')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('887', N'Йемен', N'Йеменская Республика', N'Yemen', 'YE', 'YEM')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('891', N'Сербия и Черногория', N'Сербия и Черногория', N'Serbia & Montenegro', 'CS', 'SCG')
INSERT INTO fx.Countries(CountryCode, ShortNameRus, FullNameRus, NameEng, Alfa2, Alfa3) VALUES('894', N'Замбия', N'Республика Замбия', N'Zambia', 'ZM', 'ZMB')

end
go