/*
This table contains list of countries (in Russian)
Author: Alex Zakharov
Date: 2/1/2008
*/

if not exists (select * from sysobjects where id = object_id(N'tools.Country') and xtype = 'U' )
begin

CREATE TABLE tools.Country (
	CountryId smallint not null identity(1,1),
	FullName nvarchar(512),
	ShortName nvarchar(128) not null
	CONSTRAINT PK_Country PRIMARY KEY CLUSTERED (CountryId ASC)
)		

DELETE FROM tools.Country
INSERT INTO tools.Country(ShortName) VALUES(N'Австралия') 
INSERT INTO tools.Country(ShortName) VALUES(N'Австрия') 
INSERT INTO tools.Country(ShortName) VALUES(N'Азербайджан') 
INSERT INTO tools.Country(ShortName) VALUES(N'Албания') 
INSERT INTO tools.Country(ShortName) VALUES(N'Алжир') 
INSERT INTO tools.Country(ShortName) VALUES(N'Ангола') 
INSERT INTO tools.Country(ShortName) VALUES(N'Андорра') 
INSERT INTO tools.Country(ShortName) VALUES(N'Антигуа и Барбуда') 
INSERT INTO tools.Country(ShortName) VALUES(N'Аргентина') 
INSERT INTO tools.Country(ShortName) VALUES(N'Армения') 
INSERT INTO tools.Country(ShortName) VALUES(N'Афганистан')
INSERT INTO tools.Country(ShortName) VALUES(N'Багамские Острова') 
INSERT INTO tools.Country(ShortName) VALUES(N'Бангладеш') 
INSERT INTO tools.Country(ShortName) VALUES(N'Барбадос') 
INSERT INTO tools.Country(ShortName) VALUES(N'Бахрейн') 
INSERT INTO tools.Country(ShortName) VALUES(N'Беларусь') 
INSERT INTO tools.Country(ShortName) VALUES(N'Белиз') 
INSERT INTO tools.Country(ShortName) VALUES(N'Бельгия') 
INSERT INTO tools.Country(ShortName) VALUES(N'Бенин') 
INSERT INTO tools.Country(ShortName) VALUES(N'Болгария') 
INSERT INTO tools.Country(ShortName) VALUES(N'Боливия') 
INSERT INTO tools.Country(ShortName) VALUES(N'Босния и Герцеговина') 
INSERT INTO tools.Country(ShortName) VALUES(N'Ботсвана') 
INSERT INTO tools.Country(ShortName) VALUES(N'Бразилия') 
INSERT INTO tools.Country(ShortName) VALUES(N'Бруней-Даруссалам') 
INSERT INTO tools.Country(ShortName) VALUES(N'Буркина-Фасо') 
INSERT INTO tools.Country(ShortName) VALUES(N'Бурунди') 
INSERT INTO tools.Country(ShortName) VALUES(N'Бутан') 
INSERT INTO tools.Country(ShortName) VALUES(N'Вануату') 
INSERT INTO tools.Country(ShortName) VALUES(N'Великобритания')
INSERT INTO tools.Country(ShortName) VALUES(N'Венгрия') 
INSERT INTO tools.Country(ShortName) VALUES(N'Венесуэла') 
INSERT INTO tools.Country(ShortName) VALUES(N'Вьетнам')
INSERT INTO tools.Country(ShortName) VALUES(N'Габон') 
INSERT INTO tools.Country(ShortName) VALUES(N'Гаити') 
INSERT INTO tools.Country(ShortName) VALUES(N'Гайана') 
INSERT INTO tools.Country(ShortName) VALUES(N'Гамбия') 
INSERT INTO tools.Country(ShortName) VALUES(N'Гана') 
INSERT INTO tools.Country(ShortName) VALUES(N'Гватемала') 
INSERT INTO tools.Country(ShortName) VALUES(N'Гвинея') 
INSERT INTO tools.Country(ShortName) VALUES(N'Гвинея-Бисау') 
INSERT INTO tools.Country(ShortName) VALUES(N'Германия') 
INSERT INTO tools.Country(ShortName) VALUES(N'Гондурас') 
INSERT INTO tools.Country(ShortName) VALUES(N'Гренада') 
INSERT INTO tools.Country(ShortName) VALUES(N'Греция') 
INSERT INTO tools.Country(ShortName) VALUES(N'Грузия')
INSERT INTO tools.Country(ShortName) VALUES(N'Дания') 
INSERT INTO tools.Country(ShortName) VALUES(N'Демократическая Республика Конго') 
INSERT INTO tools.Country(ShortName) VALUES(N'Джибути') 
INSERT INTO tools.Country(ShortName) VALUES(N'Доминика') 
INSERT INTO tools.Country(ShortName) VALUES(N'Доминиканская Республика')
INSERT INTO tools.Country(ShortName) VALUES(N'Египет')
INSERT INTO tools.Country(ShortName) VALUES(N'Замбия') 
INSERT INTO tools.Country(ShortName) VALUES(N'Зимбабве')
INSERT INTO tools.Country(ShortName) VALUES(N'Израиль') 
INSERT INTO tools.Country(ShortName) VALUES(N'Индия') 
INSERT INTO tools.Country(ShortName) VALUES(N'Индонезия') 
INSERT INTO tools.Country(ShortName) VALUES(N'Иордания') 
INSERT INTO tools.Country(ShortName) VALUES(N'Ирак') 
INSERT INTO tools.Country(ShortName) VALUES(N'Иран') 
INSERT INTO tools.Country(ShortName) VALUES(N'Ирландия') 
INSERT INTO tools.Country(ShortName) VALUES(N'Исландия') 
INSERT INTO tools.Country(ShortName) VALUES(N'Испания') 
INSERT INTO tools.Country(ShortName) VALUES(N'Италия')
INSERT INTO tools.Country(ShortName) VALUES(N'Йемен')
INSERT INTO tools.Country(ShortName) VALUES(N'Кабо-Верде') 
INSERT INTO tools.Country(ShortName) VALUES(N'Казахстан') 
INSERT INTO tools.Country(ShortName) VALUES(N'Камбоджа') 
INSERT INTO tools.Country(ShortName) VALUES(N'Камерун') 
INSERT INTO tools.Country(ShortName) VALUES(N'Канада') 
INSERT INTO tools.Country(ShortName) VALUES(N'Катар') 
INSERT INTO tools.Country(ShortName) VALUES(N'Кения') 
INSERT INTO tools.Country(ShortName) VALUES(N'Кипр') 
INSERT INTO tools.Country(ShortName) VALUES(N'Кирибати') 
INSERT INTO tools.Country(ShortName) VALUES(N'Китай') 
INSERT INTO tools.Country(ShortName) VALUES(N'Колумбия') 
INSERT INTO tools.Country(ShortName) VALUES(N'Коморские Острова') 
INSERT INTO tools.Country(ShortName) VALUES(N'Конго') 
INSERT INTO tools.Country(ShortName) VALUES(N'Корейская Народно-Демократическая Республика') 
INSERT INTO tools.Country(ShortName) VALUES(N'Корея')
INSERT INTO tools.Country(ShortName) VALUES(N'Коста-Рика') 
INSERT INTO tools.Country(ShortName) VALUES(N'Кот-дИвуар') 
INSERT INTO tools.Country(ShortName) VALUES(N'Куба') 
INSERT INTO tools.Country(ShortName) VALUES(N'Кувейт') 
INSERT INTO tools.Country(ShortName) VALUES(N'Кыргызстан')
INSERT INTO tools.Country(ShortName) VALUES(N'Лаос') 
INSERT INTO tools.Country(ShortName) VALUES(N'Латвия') 
INSERT INTO tools.Country(ShortName) VALUES(N'Лесото') 
INSERT INTO tools.Country(ShortName) VALUES(N'Либерия') 
INSERT INTO tools.Country(ShortName) VALUES(N'Ливан') 
INSERT INTO tools.Country(ShortName) VALUES(N'Ливия')
INSERT INTO tools.Country(ShortName) VALUES(N'Литва') 
INSERT INTO tools.Country(ShortName) VALUES(N'Лихтенштейн') 
INSERT INTO tools.Country(ShortName) VALUES(N'Люксембург')
INSERT INTO tools.Country(ShortName) VALUES(N'Маврикий') 
INSERT INTO tools.Country(ShortName) VALUES(N'Мавритания') 
INSERT INTO tools.Country(ShortName) VALUES(N'Мадагаскар') 
INSERT INTO tools.Country(ShortName) VALUES(N'Малави') 
INSERT INTO tools.Country(ShortName) VALUES(N'Малайзия') 
INSERT INTO tools.Country(ShortName) VALUES(N'Мали') 
INSERT INTO tools.Country(ShortName) VALUES(N'Мальдивские Острова') 
INSERT INTO tools.Country(ShortName) VALUES(N'Мальта') 
INSERT INTO tools.Country(ShortName) VALUES(N'Марокко') 
INSERT INTO tools.Country(ShortName) VALUES(N'Маршалловы Острова') 
INSERT INTO tools.Country(ShortName) VALUES(N'Мексика') 
INSERT INTO tools.Country(ShortName) VALUES(N'Микронезия') 
INSERT INTO tools.Country(ShortName) VALUES(N'Мозамбик') 
INSERT INTO tools.Country(ShortName) VALUES(N'Молдова')
INSERT INTO tools.Country(ShortName) VALUES(N'Монако') 
INSERT INTO tools.Country(ShortName) VALUES(N'Монголия') 
INSERT INTO tools.Country(ShortName) VALUES(N'Мьянма')
INSERT INTO tools.Country(ShortName) VALUES(N'Намибия') 
INSERT INTO tools.Country(ShortName) VALUES(N'Науру') 
INSERT INTO tools.Country(ShortName) VALUES(N'Непал') 
INSERT INTO tools.Country(ShortName) VALUES(N'Нигер') 
INSERT INTO tools.Country(ShortName) VALUES(N'Нигерия') 
INSERT INTO tools.Country(ShortName) VALUES(N'Нидерланды') 
INSERT INTO tools.Country(ShortName) VALUES(N'Никарагуа') 
INSERT INTO tools.Country(ShortName) VALUES(N'Новая Зеландия') 
INSERT INTO tools.Country(ShortName) VALUES(N'Норвегия')
INSERT INTO tools.Country(ShortName) VALUES(N'Танзания') 
INSERT INTO tools.Country(ShortName) VALUES(N'Объединенные Арабские Эмираты') 
INSERT INTO tools.Country(ShortName) VALUES(N'Оман')
INSERT INTO tools.Country(ShortName) VALUES(N'Пакистан') 
INSERT INTO tools.Country(ShortName) VALUES(N'Палау') 
INSERT INTO tools.Country(ShortName) VALUES(N'Панама') 
INSERT INTO tools.Country(ShortName) VALUES(N'Папуа-Новая Гвинея') 
INSERT INTO tools.Country(ShortName) VALUES(N'Парагвай') 
INSERT INTO tools.Country(ShortName) VALUES(N'Перу') 
INSERT INTO tools.Country(ShortName) VALUES(N'Польша') 
INSERT INTO tools.Country(ShortName) VALUES(N'Португалия')
INSERT INTO tools.Country(ShortName) VALUES(N'Российская Федерация') 
INSERT INTO tools.Country(ShortName) VALUES(N'Руанда') 
INSERT INTO tools.Country(ShortName) VALUES(N'Румыния')
INSERT INTO tools.Country(ShortName) VALUES(N'Сальвадор') 
INSERT INTO tools.Country(ShortName) VALUES(N'Самоа') 
INSERT INTO tools.Country(ShortName) VALUES(N'Сан-Марино') 
INSERT INTO tools.Country(ShortName) VALUES(N'Сан-Томе и Принсипи') 
INSERT INTO tools.Country(ShortName) VALUES(N'Саудовская Аравия') 
INSERT INTO tools.Country(ShortName) VALUES(N'Свазиленд') 
INSERT INTO tools.Country(ShortName) VALUES(N'Сейшельские Острова') 
INSERT INTO tools.Country(ShortName) VALUES(N'Сенегал') 
INSERT INTO tools.Country(ShortName) VALUES(N'Сент-Винсент и Гренадины') 
INSERT INTO tools.Country(ShortName) VALUES(N'Сент-Китс и Невис') 
INSERT INTO tools.Country(ShortName) VALUES(N'Сент-Люсия') 
INSERT INTO tools.Country(ShortName) VALUES(N'Сербия Сингапур') 
INSERT INTO tools.Country(ShortName) VALUES(N'Сирия') 
INSERT INTO tools.Country(ShortName) VALUES(N'Словакия') 
INSERT INTO tools.Country(ShortName) VALUES(N'Словения')  
INSERT INTO tools.Country(ShortName) VALUES(N'Соединенные Штаты Америки') 
INSERT INTO tools.Country(ShortName) VALUES(N'Соломоновы Острова') 
INSERT INTO tools.Country(ShortName) VALUES(N'Сомали') 
INSERT INTO tools.Country(ShortName) VALUES(N'Судан') 
INSERT INTO tools.Country(ShortName) VALUES(N'Суринам') 
INSERT INTO tools.Country(ShortName) VALUES(N'Сьерра-Леоне')
INSERT INTO tools.Country(ShortName) VALUES(N'Таджикистан') 
INSERT INTO tools.Country(ShortName) VALUES(N'Таиланд') 
INSERT INTO tools.Country(ShortName) VALUES(N'Тимор-Лешти') 
INSERT INTO tools.Country(ShortName) VALUES(N'Того') 
INSERT INTO tools.Country(ShortName) VALUES(N'Тонга') 
INSERT INTO tools.Country(ShortName) VALUES(N'Тринидад и Тобаго') 
INSERT INTO tools.Country(ShortName) VALUES(N'Тувалу') 
INSERT INTO tools.Country(ShortName) VALUES(N'Тунис') 
INSERT INTO tools.Country(ShortName) VALUES(N'Туркменистан') 
INSERT INTO tools.Country(ShortName) VALUES(N'Турция')
INSERT INTO tools.Country(ShortName) VALUES(N'Уганда') 
INSERT INTO tools.Country(ShortName) VALUES(N'Узбекистан') 
INSERT INTO tools.Country(ShortName) VALUES(N'Украина') 
INSERT INTO tools.Country(ShortName) VALUES(N'Уругвай')
INSERT INTO tools.Country(ShortName) VALUES(N'Фиджи') 
INSERT INTO tools.Country(ShortName) VALUES(N'Филиппины') 
INSERT INTO tools.Country(ShortName) VALUES(N'Финляндия') 
INSERT INTO tools.Country(ShortName) VALUES(N'Франция')
INSERT INTO tools.Country(ShortName) VALUES(N'Хорватия')
INSERT INTO tools.Country(ShortName) VALUES(N'Центральноафриканская Республика')
INSERT INTO tools.Country(ShortName) VALUES(N'Чад') 
INSERT INTO tools.Country(ShortName) VALUES(N'Чехия')
INSERT INTO tools.Country(ShortName) VALUES(N'Черногория') 
INSERT INTO tools.Country(ShortName) VALUES(N'Чили')
INSERT INTO tools.Country(ShortName) VALUES(N'Швейцария') 
INSERT INTO tools.Country(ShortName) VALUES(N'Швеция') 
INSERT INTO tools.Country(ShortName) VALUES(N'Шри-Ланка')
INSERT INTO tools.Country(ShortName) VALUES(N'Эквадор') 
INSERT INTO tools.Country(ShortName) VALUES(N'Экваториальная Гвинея') 
INSERT INTO tools.Country(ShortName) VALUES(N'Эритрея') 
INSERT INTO tools.Country(ShortName) VALUES(N'Эстония') 
INSERT INTO tools.Country(ShortName) VALUES(N'Эфиопия')
INSERT INTO tools.Country(ShortName) VALUES(N'Южная Африка')
INSERT INTO tools.Country(ShortName) VALUES(N'Ямайка') 
INSERT INTO tools.Country(ShortName) VALUES(N'Япония')

end
go