//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1378
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnjLab.FX.Properties {
    using Sys;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AnjLab.FX.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can get value only for field or property member.
        /// </summary>
        internal static string CanGetValueOnlyForFieldOrPropertyMember {
            get {
                return ResourceManager.GetString("CanGetValueOnlyForFieldOrPropertyMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can set value only for field or property member.
        /// </summary>
        internal static string CanSetValueOnlyForFieldOrPropertyMember {
            get {
                return ResourceManager.GetString("CanSetValueOnlyForFieldOrPropertyMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should be true.
        /// </summary>
        internal static string CantBeFalse {
            get {
                return ResourceManager.GetString("CantBeFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t be null.
        /// </summary>
        internal static string CantBeNull {
            get {
                return ResourceManager.GetString("CantBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t be null or empty.
        /// </summary>
        internal static string CantBeNullOrEmpty {
            get {
                return ResourceManager.GetString("CantBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find member: {0}.
        /// </summary>
        internal static string CantFindMember_Name {
            get {
                return ResourceManager.GetString("CantFindMember_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code generation error.
        /// </summary>
        internal static string CodeGenerationError {
            get {
                return ResourceManager.GetString("CodeGenerationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{1}] Daily at {0}.
        /// </summary>
        internal static string DailyAt_TimeOfDay_Tag {
            get {
                return ResourceManager.GetString("DailyAt_TimeOfDay_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{1}] every {0} starting from {2}.
        /// </summary>
        internal static string EveryTimeStartingFrom_Interval_Tag_StartTime {
            get {
                return ResourceManager.GetString("EveryTimeStartingFrom_Interval_Tag_StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{1}] Hourly at {0} min.
        /// </summary>
        internal static string HourlyAt_Minutes_Tag {
            get {
                return ResourceManager.GetString("HourlyAt_Minutes_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{1}] monthly every {2} day at {0}.
        /// </summary>
        internal static string MonthlyEveryDayAt_TimeOfDay_Tag_DateTime {
            get {
                return ResourceManager.GetString("MonthlyEveryDayAt_TimeOfDay_Tag_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{1}] Once at {0}.
        /// </summary>
        internal static string OnceAt_Time_Tag {
            get {
                return ResourceManager.GetString("OnceAt_Time_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should be between [{0},{1}].
        /// </summary>
        internal static string ShouldBeBetween_A_B {
            get {
                return ResourceManager.GetString("ShouldBeBetween_A_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should be greater then {1}, but was {0}.
        /// </summary>
        internal static string ShouldBeGreater_A_B {
            get {
                return ResourceManager.GetString("ShouldBeGreater_A_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should be greater then zero.
        /// </summary>
        internal static string ShouldBeGreaterThenZero {
            get {
                return ResourceManager.GetString("ShouldBeGreaterThenZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{1}] Weekly on {0} at {2}.
        /// </summary>
        internal static string Weekly_OnTime_AtTimeOfDay_Tag {
            get {
                return ResourceManager.GetString("Weekly_OnTime_AtTimeOfDay_Tag", resourceCulture);
            }
        }
    }
}
