//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnjLab.FX.Tests.Properties {
    using Sys;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AnjLab.FX.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;feed xmlns:gr=&quot;http://www.google.com/schemas/reader/atom/&quot; xmlns:media=&quot;http://search.yahoo.com/mrss/&quot; xmlns=&quot;http://www.w3.org/2005/Atom&quot;&gt;
        ///  &lt;!--
        ///Content-type: Preventing XSRF in IE.
        ///
        ///--&gt;
        ///  &lt;generator uri=&quot;http://www.google.com/reader&quot;&gt;Google Reader&lt;/generator&gt;
        ///  &lt;id&gt;tag:google.com,2005:reader/user/08735471787465251095/label/test&lt;/id&gt;
        ///  &lt;title&gt;&quot;test&quot; via Yury in Google Reader&lt;/title&gt;
        ///  &lt;link rel=&quot;self&quot; href=&quot;http://www.google.com/reader/atom/user/0873547178 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AtomFeed1 {
            get {
                return ResourceManager.GetString("AtomFeed1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;feed xmlns:gr=&quot;http://www.google.com/schemas/reader/atom/&quot; xmlns:media=&quot;http://search.yahoo.com/mrss/&quot; xmlns=&quot;http://www.w3.org/2005/Atom&quot;&gt;
        ///  &lt;!--
        ///Content-type: Preventing XSRF in IE.
        ///
        ///--&gt;
        ///  &lt;generator uri=&quot;http://www.google.com/reader&quot;&gt;Google Reader&lt;/generator&gt;
        ///  &lt;id&gt;tag:google.com,2005:reader/user/08735471787465251095/label/test&lt;/id&gt;
        ///  &lt;title&gt;&quot;test&quot; via Yury in Google Reader&lt;/title&gt;
        ///  &lt;link rel=&quot;self&quot; href=&quot;http://www.google.com/reader/atom/user/08735471787465251095/label/t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AtomFeed2 {
            get {
                return ResourceManager.GetString("AtomFeed2", resourceCulture);
            }
        }
    }
}
